using System;

public enum ImageNames
{
	LocalButton,
	OnlineButton,
	HowToPlayButton,
	FreeplayButton,
	HostHeader,
	PublicHeader,
	PrivateHeader,
	KillButton,
	ReportButton,
	UseButton,
	SabotageButton,
	CamsButton,
	AdminMapButton,
	MIRAAdminButton,
	PolusAdminButton,
	DoorLogsButton,
	VentButton,
	VitalsButton,
	StartButton,
	PublicButton,
	PrivateButton,
	PlayAgainButton,
	ExitRoomButton,
	OptionsButton,
	DiscussHeader,
	ShhhHeader,
	IVotedBadge,
	SkipVoteButton,
	MiraTaskBeginButton,
	SkippedVoteTallyHeader,
	ShopSkinsBanner,
	ShopHatsBanner,
	ShopPetsBanner,
	EmergencyMeetingText,
	AnnouncementsText,
	DeadBodyReportedText,
	ProceedButton,
	AirshipAdminButton = 39
}
