//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Submerged.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Submerged.Localization.Strings.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Art.
        /// </summary>
        internal static string Credits_AdditionalArt {
            get {
                return ResourceManager.GetString("Credits.AdditionalArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        internal static string Credits_Artists {
            get {
                return ResourceManager.GetString("Credits.Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        internal static string Credits_Developers {
            get {
                return ResourceManager.GetString("Credits.Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Design.
        /// </summary>
        internal static string Credits_MapDesign {
            get {
                return ResourceManager.GetString("Credits.MapDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Lead.
        /// </summary>
        internal static string Credits_ProjectLead {
            get {
                return ResourceManager.GetString("Credits.ProjectLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support.
        /// </summary>
        internal static string Credits_TechnicalSupport {
            get {
                return ResourceManager.GetString("Credits.TechnicalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        internal static string Credits_Translators {
            get {
                return ResourceManager.GetString("Credits.Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load Submerged assets. Please restart your game.
        ///If this problem persists, please reinstall Submerged or open an issue on GitHub..
        /// </summary>
        internal static string Error_AssetsNotLoaded {
            get {
                return ResourceManager.GetString("Error.AssetsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start the game as the following players do not have Submerged:.
        /// </summary>
        internal static string Error_PlayersMissingSubmerged {
            get {
                return ResourceManager.GetString("Error.PlayersMissingSubmerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submerged: An underwater map with a multi-floor system, elevators, new tasks and sabotages, and more!.
        /// </summary>
        internal static string SubmergedTooltip {
            get {
                return ResourceManager.GetString("SubmergedTooltip", resourceCulture);
            }
        }
    }
}
