//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Submerged.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Submerged.Localization.Strings.Locations", typeof(Locations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballast.
        /// </summary>
        internal static string Ballast {
            get {
                return ResourceManager.GetString("Ballast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central.
        /// </summary>
        internal static string Central {
            get {
                return ResourceManager.GetString("Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Central.
        /// </summary>
        internal static string Central_Lower {
            get {
                return ResourceManager.GetString("Central.Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Central.
        /// </summary>
        internal static string Central_Upper {
            get {
                return ResourceManager.GetString("Central.Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Deck.
        /// </summary>
        internal static string Deck_Lower {
            get {
                return ResourceManager.GetString("Deck.Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Deck.
        /// </summary>
        internal static string Deck_Upper {
            get {
                return ResourceManager.GetString("Deck.Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Elevators.
        /// </summary>
        internal static string Elevators_East {
            get {
                return ResourceManager.GetString("Elevators.East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Elevator.
        /// </summary>
        internal static string Elevators_Service {
            get {
                return ResourceManager.GetString("Elevators.Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Elevators.
        /// </summary>
        internal static string Elevators_West {
            get {
                return ResourceManager.GetString("Elevators.West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtration.
        /// </summary>
        internal static string Filtration {
            get {
                return ResourceManager.GetString("Filtration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string Lobby {
            get {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Lobby.
        /// </summary>
        internal static string Lobby_Lower {
            get {
                return ResourceManager.GetString("Lobby.Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Lobby.
        /// </summary>
        internal static string Lobby_Upper {
            get {
                return ResourceManager.GetString("Lobby.Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observatory.
        /// </summary>
        internal static string Observatory {
            get {
                return ResourceManager.GetString("Observatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        internal static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
    }
}
