//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Submerged.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tasks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tasks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Submerged.Localization.Strings.Tasks", typeof(Tasks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        internal static string CamsSabotage_Active {
            get {
                return ResourceManager.GetString("CamsSabotage.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISABLED.
        /// </summary>
        internal static string CamsSabotage_Disabled {
            get {
                return ResourceManager.GetString("CamsSabotage.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPAIRING.
        /// </summary>
        internal static string CamsSabotage_Repairing {
            get {
                return ResourceManager.GetString("CamsSabotage.Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Glass.
        /// </summary>
        internal static string CleanGlass {
            get {
                return ResourceManager.GetString("CleanGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Urchins.
        /// </summary>
        internal static string ClearUrchins {
            get {
                return ResourceManager.GetString("ClearUrchins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Reactor.
        /// </summary>
        internal static string CycleReactor {
            get {
                return ResourceManager.GetString("CycleReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM:{0}.
        /// </summary>
        internal static string CycleReactor_RPM {
            get {
                return ResourceManager.GetString("CycleReactor.RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose Elevators.
        /// </summary>
        internal static string DiagnoseElevators {
            get {
                return ResourceManager.GetString("DiagnoseElevators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIAGNOSE.
        /// </summary>
        internal static string DiagnoseElevators_Diagnose {
            get {
                return ResourceManager.GetString("DiagnoseElevators.Diagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispense Water.
        /// </summary>
        internal static string DispenseWater {
            get {
                return ResourceManager.GetString("DispenseWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Pet Fish.
        /// </summary>
        internal static string FeedPetFish {
            get {
                return ResourceManager.GetString("FeedPetFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify Specimen.
        /// </summary>
        internal static string IdentifySpecimen {
            get {
                return ResourceManager.GetString("IdentifySpecimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moral support puffer.
        /// </summary>
        internal static string IdentifySpecimen_Pufferfish {
            get {
                return ResourceManager.GetString("IdentifySpecimen.Pufferfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Volcanic Activity.
        /// </summary>
        internal static string LocateVolcanicActivity {
            get {
                return ResourceManager.GetString("LocateVolcanicActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conical Stratovolcano
        ///Height: 7,800 feet
        ///Status: Active
        ///Risk: Low.
        /// </summary>
        internal static string LocateVolcanicActivity_Complete {
            get {
                return ResourceManager.GetString("LocateVolcanicActivity.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conical Stratovolcano
        ///Height: 7,800 feet
        ///Status: Active
        ///Risk: IMMINENT.
        /// </summary>
        internal static string LocateVolcanicActivity_Incomplete {
            get {
                return ResourceManager.GetString("LocateVolcanicActivity.Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microwave Lunch.
        /// </summary>
        internal static string MicrowaveLunch {
            get {
                return ResourceManager.GetString("MicrowaveLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook: {0}s
        ///Note to self:
        ///Collect when
        ///      done
        ///.
        /// </summary>
        internal static string MicrowaveLunch_CookTime {
            get {
                return ResourceManager.GetString("MicrowaveLunch.CookTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to clean after use.
        ///
        ///  - Green
        ///     &amp; Lime.
        /// </summary>
        internal static string MicrowaveLunch_PostItGreen {
            get {
                return ResourceManager.GetString("MicrowaveLunch.PostItGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t eat my slice of pizza!
        ///        - Pink.
        /// </summary>
        internal static string MicrowaveLunch_PostItPink {
            get {
                return ResourceManager.GetString("MicrowaveLunch.PostItPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}.
        /// </summary>
        internal static string MicrowaveLunch_TaskTimer {
            get {
                return ResourceManager.GetString("MicrowaveLunch.TaskTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mop Puddles.
        /// </summary>
        internal static string MopPuddles {
            get {
                return ResourceManager.GetString("MopPuddles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygenate Sea Plants.
        /// </summary>
        internal static string OxygenateSeaPlants {
            get {
                return ResourceManager.GetString("OxygenateSeaPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug Leaks.
        /// </summary>
        internal static string PlugLeaks {
            get {
                return ResourceManager.GetString("PlugLeaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Breakfast.
        /// </summary>
        internal static string PurchaseBreakfast {
            get {
                return ResourceManager.GetString("PurchaseBreakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFERS:.
        /// </summary>
        internal static string PurchaseBreakfast_Offers {
            get {
                return ResourceManager.GetString("PurchaseBreakfast.Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect Piping.
        /// </summary>
        internal static string ReconnectPiping {
            get {
                return ResourceManager.GetString("ReconnectPiping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;size=125%&gt;HIGH&lt;/size&gt;
        ///PRESSURE&lt;/b&gt;.
        /// </summary>
        internal static string ReconnectPiping_HighPressure {
            get {
                return ResourceManager.GetString("ReconnectPiping.HighPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Nav Beacon Data.
        /// </summary>
        internal static string RecordNavBeaconData {
            get {
                return ResourceManager.GetString("RecordNavBeaconData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message received..
        /// </summary>
        internal static string RecordNavBeaconData_Done {
            get {
                return ResourceManager.GetString("RecordNavBeaconData.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Navigation
        ///Beacon Coordinates.
        /// </summary>
        internal static string RecordNavBeaconData_Enter {
            get {
                return ResourceManager.GetString("RecordNavBeaconData.Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming message....
        /// </summary>
        internal static string RecordNavBeaconData_Wait {
            get {
                return ResourceManager.GetString("RecordNavBeaconData.Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Breakers.
        /// </summary>
        internal static string ResetBreakers {
            get {
                return ResourceManager.GetString("ResetBreakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reshelve Books.
        /// </summary>
        internal static string ReshelveBooks {
            get {
                return ResourceManager.GetString("ReshelveBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;A&lt;/size&gt;quarium Care.
        /// </summary>
        internal static string ReshelveBooks_Book01 {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;B&lt;/size&gt;enthic Beasts.
        /// </summary>
        internal static string ReshelveBooks_Book02_Lounge {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book02-Lounge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;C&lt;/size&gt;avern Critters.
        /// </summary>
        internal static string ReshelveBooks_Book03 {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;E&lt;/size&gt;xotic Sea Life.
        /// </summary>
        internal static string ReshelveBooks_Book04 {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;F&lt;/size&gt;inding Grimo.
        /// </summary>
        internal static string ReshelveBooks_Book05 {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;I&lt;/size&gt;chthyology 101.
        /// </summary>
        internal static string ReshelveBooks_Book06_Lounge {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book06-Lounge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;J&lt;/size&gt;immy The Sail Fish.
        /// </summary>
        internal static string ReshelveBooks_Book07 {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;K&lt;/size&gt;epler Worms.
        /// </summary>
        internal static string ReshelveBooks_Book08_Medical {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book08-Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;M&lt;/size&gt;angrove
        ///Monday.
        /// </summary>
        internal static string ReshelveBooks_Book09 {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;N&lt;/size&gt;autical Nonsense.
        /// </summary>
        internal static string ReshelveBooks_Book10_Medical {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book10-Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;O&lt;/size&gt;ctopus Digest.
        /// </summary>
        internal static string ReshelveBooks_Book11_Lounge {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book11-Lounge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;P&lt;/size&gt;incer Danger!.
        /// </summary>
        internal static string ReshelveBooks_Book12 {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;S&lt;/size&gt;ea Slugs &amp; You!.
        /// </summary>
        internal static string ReshelveBooks_Book13_Medical {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book13-Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;V&lt;/size&gt;enomous
        ///Floaters.
        /// </summary>
        internal static string ReshelveBooks_Book14 {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=125%&gt;W&lt;/size&gt;ailing Waters.
        /// </summary>
        internal static string ReshelveBooks_Book15 {
            get {
                return ResourceManager.GetString("ReshelveBooks.Book15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Oxygen Mask.
        /// </summary>
        internal static string RetrieveOxygenMask {
            get {
                return ResourceManager.GetString("RetrieveOxygenMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot Depth Charges.
        /// </summary>
        internal static string ShootDepthCharges {
            get {
                return ResourceManager.GetString("ShootDepthCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Remaining: {0}.
        /// </summary>
        internal static string ShootDepthCharges_Remaining {
            get {
                return ResourceManager.GetString("ShootDepthCharges.Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Scuba Gear.
        /// </summary>
        internal static string SortScubaGear {
            get {
                return ResourceManager.GetString("SortScubaGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... ({0}/{1}).
        /// </summary>
        internal static string SpawnIn_Bottom_Loading {
            get {
                return ResourceManager.GetString("SpawnIn.Bottom.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready Players: {0}/{1}.
        /// </summary>
        internal static string SpawnIn_Bottom_Spawning {
            get {
                return ResourceManager.GetString("SpawnIn.Bottom.Spawning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Other Players....
        /// </summary>
        internal static string SpawnIn_Top_LoadingClicked {
            get {
                return ResourceManager.GetString("SpawnIn.Top.LoadingClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Other Players... ({0}s).
        /// </summary>
        internal static string SpawnIn_Top_SpawningClicked {
            get {
                return ResourceManager.GetString("SpawnIn.Top.SpawningClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the Impostor... ({0}s).
        /// </summary>
        internal static string SpawnIn_Top_SpawningHnS {
            get {
                return ResourceManager.GetString("SpawnIn.Top.SpawningHnS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining: {0}s.
        /// </summary>
        internal static string SpawnIn_Top_SpawningNotClicked {
            get {
                return ResourceManager.GetString("SpawnIn.Top.SpawningNotClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot Whale Shark.
        /// </summary>
        internal static string SpotWhaleShark {
            get {
                return ResourceManager.GetString("SpotWhaleShark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Range {0}s.
        /// </summary>
        internal static string SpotWhaleShark_InRange {
            get {
                return ResourceManager.GetString("SpotWhaleShark.InRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Visible {0}s.
        /// </summary>
        internal static string SpotWhaleShark_NotVisible {
            get {
                return ResourceManager.GetString("SpotWhaleShark.NotVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilize Water Levels.
        /// </summary>
        internal static string StabilizeWaterLevels {
            get {
                return ResourceManager.GetString("StabilizeWaterLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Submersible.
        /// </summary>
        internal static string StartSubmersible {
            get {
                return ResourceManager.GetString("StartSubmersible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUX ENGINES.
        /// </summary>
        internal static string StartSubmersible_AuxEngines {
            get {
                return ResourceManager.GetString("StartSubmersible.AuxEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXT. SYSTEMS.
        /// </summary>
        internal static string StartSubmersible_ExternalSystems {
            get {
                return ResourceManager.GetString("StartSubmersible.ExternalSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN ENGINES.
        /// </summary>
        internal static string StartSubmersible_MainEngines {
            get {
                return ResourceManager.GetString("StartSubmersible.MainEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIELDS.
        /// </summary>
        internal static string StartSubmersible_Shields {
            get {
                return ResourceManager.GetString("StartSubmersible.Shields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Active.
        /// </summary>
        internal static string StartSubmersible_Status_Active {
            get {
                return ResourceManager.GetString("StartSubmersible.Status.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Inactive.
        /// </summary>
        internal static string StartSubmersible_Status_Inactive {
            get {
                return ResourceManager.GetString("StartSubmersible.Status.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Starting....
        /// </summary>
        internal static string StartSubmersible_Status_Starting {
            get {
                return ResourceManager.GetString("StartSubmersible.Status.Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEAPONS.
        /// </summary>
        internal static string StartSubmersible_Weapons {
            get {
                return ResourceManager.GetString("StartSubmersible.Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steady Heartbeat.
        /// </summary>
        internal static string SteadyHeartbeat {
            get {
                return ResourceManager.GetString("SteadyHeartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart
        ///Rate.
        /// </summary>
        internal static string SteadyHeartbeat_BPMLeft {
            get {
                return ResourceManager.GetString("SteadyHeartbeat.BPMLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///BPM.
        /// </summary>
        internal static string SteadyHeartbeat_BPMRight {
            get {
                return ResourceManager.GetString("SteadyHeartbeat.BPMRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        internal static string SteadyHeartbeat_Status {
            get {
                return ResourceManager.GetString("SteadyHeartbeat.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular.
        /// </summary>
        internal static string SteadyHeartbeat_Status_Irregular {
            get {
                return ResourceManager.GetString("SteadyHeartbeat.Status.Irregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilizing.
        /// </summary>
        internal static string SteadyHeartbeat_Status_Stabilizing {
            get {
                return ResourceManager.GetString("SteadyHeartbeat.Status.Stabilizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable.
        /// </summary>
        internal static string SteadyHeartbeat_Status_Stable {
            get {
                return ResourceManager.GetString("SteadyHeartbeat.Status.Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;u&gt;Patient Notes&lt;/u&gt;
        ///
        ///Normal
        ///Heart Rate:
        ///{0} - {1} BPM.
        /// </summary>
        internal static string SteadyHeartbeat_Target {
            get {
                return ResourceManager.GetString("SteadyHeartbeat.Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Manta Ray.
        /// </summary>
        internal static string TrackMantaRay {
            get {
                return ResourceManager.GetString("TrackMantaRay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking: {0}%.
        /// </summary>
        internal static string TrackMantaRay_Tracking {
            get {
                return ResourceManager.GetString("TrackMantaRay.Tracking", resourceCulture);
            }
        }
    }
}
