public enum TaskTypes
{
	PlugLeaks = 0x80,
	WhaleShark = 0x81,
	MicrowaveLunch = 0x82,
	ReshelveBooks = 0x83,
	SetNavBeacon = 0x84,
	MopPuddles = 0x85,
	OxygenateCoral = 0x86,
	ClearUrchins = 0x87,
	ShootDepthCharges = 0x88,
	DiagnoseElevators = 0x89,
	SubmarineAlignTelescope = 0x8A,
	PurchaseBreakfast = 0x8B,
	ReconnectPiping = 0x8C,
	CleanGlass = 0x8D,
	IdentifySpecimen = 0x8E,
	StartSubmersible = 0x8F,
	TrackManta = 0x90,
	DispenseWater = 0x91,
	SteadyHeartbeat = 0x92,
	FeedPetFish = 0x93,
	SortScubaGear = 0x94,
	CycleReactor = 0x95,
	RestartBreakers = 0x96,
	LocateVolcanicActivity = 0x97,
	RetrieveMask = 0x98,

	// ReSharper disable InconsistentNaming
	SubmitScan = 0,
	PrimeShields,
	FuelEngines,
	ChartCourse,
	StartReactor,
	SwipeCard,
	ClearAsteroids,
	UploadData,
	InspectSample,
	EmptyChute,
	EmptyGarbage,
	AlignEngineOutput,
	FixWiring,
	CalibrateDistributor,
	DivertPower,
	UnlockManifolds,
	ResetReactor,
	FixLights,
	CleanO2Filter,
	FixComms,
	RestoreOxy,
	StabilizeSteering,
	AssembleArtifact,
	SortSamples,
	MeasureWeather,
	EnterIdCode,
	BuyBeverage,
	ProcessData,
	RunDiagnostics,
	WaterPlants,
	MonitorOxygen,
	StoreArtifacts,
	FillCanisters,
	ActivateWeatherNodes,
	InsertKeys,
	ResetSeismic,
	ScanBoardingPass,
	OpenWaterways,
	ReplaceWaterJug,
	RepairDrill,
	AlignTelescope,
	RecordTemperature,
	RebootWifi,
	PolishRuby,
	ResetBreakers,
	Decontaminate,
	MakeBurger,
	UnlockSafe,
	SortRecords,
	PutAwayPistols,
	FixShower,
	CleanToilet,
	DressMannequin,
	PickUpTowels,
	RewindTapes,
	StartFans,
	DevelopPhotos,
	GetBiggolSword,
	PutAwayRifles,
	StopCharles,
}
